spring:
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
      
discodeit:
  repository:
    type: file   # jcf | file
    file-directory: .discodeit

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: validate  #create, create-drop, validate, none
      #    show-sql: true
      format_sql: true


logging.level:
  org.hibernate.SQL: debug



