spring:
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
datasource:
  url: jdbc:postgresql://localhost:5432/your_database_name
  username: your_username
  password: your_password
  driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # 또는 create, create-drop, validate, none
    show-sql: true  # SQL 쿼리 로그 출력 (개발 시 유용)

discodeit:
  repository:
    type: file   # jcf | file
    file-directory: .discodeit